name: Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt pyinstaller
        pyinstaller src/main.spec
        src/dist/main.exe
        
    - uses: actions/upload-artifact@v3
      with:
        name: main
        path: dist/main.exe